/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ReentrancyGuardTransient,
  ReentrancyGuardTransientInterface,
} from "../../../../@openzeppelin/contracts/utils/ReentrancyGuardTransient";

const _abi = [
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
] as const;

export class ReentrancyGuardTransient__factory {
  static readonly abi = _abi;
  static createInterface(): ReentrancyGuardTransientInterface {
    return new utils.Interface(_abi) as ReentrancyGuardTransientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrancyGuardTransient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ReentrancyGuardTransient;
  }
}
