/*
 * Copyright (c) 2021 Elastos Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.elastos.essentials.plugins.intent;

import org.apache.cordova.CallbackContext;
import org.json.JSONObject;

public class IntentInfo {

    public static final int JWT = 1;
    public static final int URL = 2;

    public static final String INTERNAL = "INTERNAL";
    public static final String EXTERNAL = "EXTERNAL";

    public static final String REDIRECT_URL = "redirecturl";
    public static final String CALLBACK_URL = "callbackurl";

    String action; // Full action as given by the dapp, including domain and action
    String params;
    String from;
    long intentId;
    CallbackContext callbackContext;

    String responseJwt = null; // JWT output generated by the dapp or service that has handled the intent.
    String originalJwtRequest = null;
    String redirecturl = null;
    String callbackurl = null;
    String aud = null;
    String req = null;
    int type = URL;


    public IntentInfo(String action, String params, CallbackContext callbackContext) {
        this.action = action;
        this.params = params;
        this.from = INTERNAL;
        this.intentId = System.currentTimeMillis(); //Need check the same time action?
        this.callbackContext = callbackContext;
    }
}
