
// DO NOT EDIT - GENERATED BY set_env.ts
export const environment = {
  "production": true,
  "RedPackets": {
    "webUrl": "https://packet.fun",
    "serviceUrl": "https://api.packet.fun/api/v1"
  }
};
