
// DO NOT EDIT - GENERATED BY set_env.ts
export const environment = {
  "production": false,
  "RedPackets": {
    "webUrl": "https://packet.fun",
    "serviceUrl": "https://192.168.1.4:5080/api/v1"
  }
};
