export enum App {
    DID_SESSIONS = "didsessions",
    LAUNCHER = "launcher",
    IDENTITY = "identity",
    CONTACTS = "contacts",
    WALLET = "wallet",
    VOTING = "voting",
    CRCOUNCIL_VOTING = "crcouncilvoting",
    CRCOUNCIL_MANAGER = "crcouncilmanager",
    CRPROPOSAL_VOTING = "crproposalvoting",
    CRSUGGESTION = "crsuggestion",
    DEVELOPER_TOOLS = "developertools",
    DPOS_VOTING = "dposvoting",
    DPOS_REGISTRATION = "dposregistration",
    HIVE_MANAGER = "hivemanager",
    SETTINGS = "settings",
    SCANNER = "scanner",
    DAPP_BROWSER = "dappbrowser",
    RED_PACKETS = "redpackets"
}