export enum App {
    DID_SESSIONS = "didsessions",
    LAUNCHER = "launcher",
    IDENTITY = "identity",
    CONTACTS = "contacts",
    WALLET = "wallet",
    VOTING = "voting",
    CRCOUNCIL_VOTING = "crcouncilvoting",
    CRPROPOSAL_VOTING = "crproposalvoting",
    CRSUGGESTION = "crsuggestion",
    DEVELOPER_TOOLS = "developertools",
    DPOS_VOTING = "dposvoting",
    DPOS_REGISTRATION = "dposregistration",
    STAKING = "staking",
    HIVE_MANAGER = "hivemanager",
    SETTINGS = "settings",
    SCANNER = "scanner",
    DAPP_BROWSER = "dappbrowser",
    RED_PACKETS = "redpackets",
    SECURITY = "security",
    MIGRATOR = "migrator",
    EASY_BRIDGE = "easy_bridge",
    MULTI_SWAP = "multi_swap",
    ELASTOS_STAKING = "elastosstaking"
}